name: Pre-merge

on: push

jobs:
  reproducer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Verdaccio Config
        run: |
          sed -i 's/^# - localhost:4873$/- localhost:4873/g' verdaccio.yml
          sed -i 's/^- "\[::1\]:4873"$/# - "[::1]:4873"/g' verdaccio.yml

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install net-tools
        run: sudo apt install net-tools

      - name: Run verdaccio & Wait for it
        run: |
          # Start Verdaccio
          npx verdaccio --config verdaccio.yml &

          # Wait for verdaccio for up to 10 seconds on IPv4 port
          npx wait-on http://localhost:4873 --timeout 10000
        continue-on-error: true

      - name: Print open ports
        run: netstat -ano
      - name: Check Verdaccio port
        run: |
          if netstat -tuln | grep 4873; then
            echo "Verdaccio is listening on port 4873"
          else
            echo "Verdaccio is not listening on port 4873"
          fi
