name: Pre-merge

on: [pull_request, push]

jobs:
  reproducer:
    runs-on: ubuntu-latest
    steps:

      - name: Print open ports
        run: ping localhost
      # Check IPv4 ports
      #- name: Print open ports  
      # run: netstat -tuln | grep 4873
